package com.iopex.imarket.utils;


public enum HeaderList {
	
	COMPANY_NAME("COMPANY_NAME"),
	CONTACT_PERSON_1("CONTACT_PERSON_1"),
	CONTACT_JOB_TITLE_1("CONTACT_JOB_TITLE_1"),
	CONTACT_EMAIL_ADDRESS_1("CONTACT_EMAIL_ADDRESS_1"),
	CONTACT_PHONE_1("CONTACT_PHONE_1"),
	CONTACT_PERSON_2("CONTACT_PERSON_2"),
	CONTACT_JOB_TITLE_2("CONTACT_JOB_TITLE_2"),
	CONTACT_EMAIL_ADDRESS_2("CONTACT_EMAIL_ADDRESS_2"),
	CONTACT_PHONE_2("CONTACT_PHONE_2"),
	CONTACT_PERSON_3("CONTACT_PERSON_3"),
	CONTACT_JOB_TITLE_3("CONTACT_JOB_TITLE_3"),
	CONTACT_EMAIL_ADDRESS_3("CONTACT_EMAIL_ADDRESS_3"),
	CONTACT_PHONE_3("CONTACT_PHONE_3"),
	INDUSTRY("INDUSTRY"),
	EMPLOYEE_COUNT("EMPLOYEE_COUNT"),
	COMPANY_WEBSITE("COMPANY_WEBSITE"),
    COUNTRY("COUNTRY"),
    COMPANY_EMAIL("COMPANY_EMAIL"),
    REVENUE("REVENUE"),
    LEAD_SOURCE("LEAD_SOURCE");

    private String header;

    HeaderList(String header) {
        this.header = header;
    }

    public String header() {
        return header;
    }
}